application: blogexample
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
  
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: blog.application

