application: pittwhiteboard
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /documents
  static_dir: documents

- url: /.*
  script: pittwhiteboard.app