application: chatroomexample
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: test

libraries:
- name: webapp2
  version: latest
  
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts  

- url: /img
  static_dir: img   

- url: /.*
  script: chatroom.application

